User: bitcoin

Env:
 - BITCOIN_VERSION : 0.11.2
 - RPCUSER         : bitcoin
 - RPCPASS         : 654Q43GPvRayNpDbZL4rAdsW4GE2fSaejubcGcuwp1c4
 - RPCPORT         : 8332
 - BITCOIN_PORT    : 8333

Expose: $BITCOIN_PORT

Add: http://www.bitcoinunlimited.info/downloads/bitcoinUnlimited-$BITCOIN_VERSION-linux64.tar.gz : /home/bitcoin/

Run: |
 # Unpacking Bitcoin Executable
 cd /home/bitcoin/
 tar xzvf bitcoinUnlimited-$BITCOIN_VERSION-linux64.tar.gz
 chown -R bitcoin:bitcoin .

Daemon:
 - bitcoind : |
     /home/bitcoin/bitcoinUnlimited-$BITCOIN_VERSION/bin/bitcoind \
       -server                                                    \
       -txindex                                                   \
       -rpcuser=$RPCUSER                                          \
       -rpcpassword=$RPCPASS                                      \
       -rpcport=$RPCPORT
 
Cron:
 - block-height     : /home/bitcoin/bitcoinUnlimited-$BITCOIN_VERSION/bin/bitcoin-cli -rpcuser=$RPCUSER -rpcpassword=$RPCPASS -rpcport=$RPCPORT getblockcount
 - connection-count : /home/bitcoin/bitcoinUnlimited-$BITCOIN_VERSION/bin/bitcoin-cli -rpcuser=$RPCUSER -rpcpassword=$RPCPASS -rpcport=$RPCPORT getconnectioncount

Volume: /home/bitcoin/.bitcoin

